export const FESTS = [
  {
    id: 1,
    name: 'Mood Indigo',
    college: 'IIT Bombay',
    date: 'Dec 20–22',
    category: 'Cultural',
    attendees: '50,000+',
    events: 200,
    color: '#fef3c7',
    emoji: '🎭',
    location: 'Powai, Mumbai',
    description: "Asia's largest college cultural festival",
  },
  {
    id: 2,
    name: 'Techfest',
    college: 'IIT Bombay',
    date: 'Jan 10–12',
    category: 'Technical',
    attendees: '1,75,000+',
    events: 150,
    color: '#ede9fe',
    emoji: '🚀',
    location: 'Powai, Mumbai',
    description: "Asia's largest science and technology festival",
  },
  {
    id: 3,
    name: 'Malhar',
    college: "St. Xavier's",
    date: 'Jul 28–30',
    category: 'Cultural',
    attendees: '30,000+',
    events: 120,
    color: '#fce7f3',
    emoji: '🎤',
    location: 'Fort, Mumbai',
    description: "Mumbai's oldest and most prestigious college fest",
  },
  {
    id: 4,
    name: 'Confluence',
    college: 'SP Jain',
    date: 'Sep 12–13',
    category: 'Business',
    attendees: '5,000+',
    events: 25,
    color: '#fff7ed',
    emoji: '💼',
    location: 'Matunga, Mumbai',
    description: 'Premier business and management conclave',
  },
  {
    id: 5,
    name: 'Umang',
    college: 'NMIMS',
    date: 'Oct 8–10',
    category: 'Cultural',
    attendees: '15,000+',
    events: 60,
    color: '#f0f9ff',
    emoji: '✨',
    location: 'Vile Parle, Mumbai',
    description: "NMIMS' flagship cultural extravaganza",
  },
  {
    id: 6,
    name: 'ECell Summit',
    college: 'IIT Bombay',
    date: 'Nov 15',
    category: 'Business',
    attendees: '8,000+',
    events: 10,
    color: '#fefce8',
    emoji: '💡',
    location: 'Powai, Mumbai',
    description: 'Annual entrepreneurship and startup summit',
  },
  {
    id: 7,
    name: 'Aavhan',
    college: 'VJTI',
    date: 'Mar 7–9',
    category: 'Technical',
    attendees: '12,000+',
    events: 45,
    color: '#ecfdf5',
    emoji: '⚡',
    location: 'Matunga, Mumbai',
    description: "VJTI's premier annual technical festival",
  },
  {
    id: 8,
    name: 'Cascade',
    college: 'ICT Mumbai',
    date: 'Feb 18–19',
    category: 'Technical',
    attendees: '6,000+',
    events: 30,
    color: '#e0f2fe',
    emoji: '🔬',
    location: 'Matunga, Mumbai',
    description: 'Science and innovation festival by ICT Mumbai',
  },
]

export const CATEGORIES = [
  { name: 'Cultural',  count: 45, emoji: '🎭', from: '#fff0f3', to: '#ffe4e6' },
  { name: 'Technical', count: 32, emoji: '⚡', from: '#f5f3ff', to: '#ede9fe' },
  { name: 'Sports',    count: 28, emoji: '🏆', from: '#f0fdf4', to: '#dcfce7' },
  { name: 'Music',     count: 19, emoji: '🎵', from: '#fffbeb', to: '#fef3c7' },
  { name: 'Business',  count: 15, emoji: '💼', from: '#eff6ff', to: '#dbeafe' },
  { name: 'Gaming',    count: 12, emoji: '🎮', from: '#f5f3ff', to: '#e0e7ff' },
  { name: 'Fashion',   count: 8,  emoji: '👗', from: '#fdf4ff', to: '#fae8ff' },
  { name: 'Literary',  count: 11, emoji: '📚', from: '#f0fdfa', to: '#ccfbf1' },
]

export const COLLEGES = [
  { name: 'IIT Bombay',   fests: 5, area: 'Powai',       emoji: '🏛️' },
  { name: 'VJTI',         fests: 3, area: 'Matunga',     emoji: '⚙️' },
  { name: 'NMIMS',        fests: 4, area: 'Vile Parle',  emoji: '📊' },
  { name: "St. Xavier's", fests: 2, area: 'Fort',        emoji: '✝️' },
  { name: 'SP Jain',      fests: 3, area: 'Matunga',     emoji: '💼' },
  { name: 'ICT Mumbai',   fests: 2, area: 'Matunga',     emoji: '🔬' },
  { name: 'KJ Somaiya',   fests: 2, area: 'Vidyavihar',  emoji: '🌿' },
  { name: 'Thadomal',     fests: 1, area: 'Bandra',      emoji: '💻' },
]
